* ravel vs flatten
 1. flatten - 새로운 ndarray 반환
 2. ravel - 기존 ndarray의 원소를 유지

In [1]:
import numpy as np

In [2]:
arr = np.arange(50).reshape(5, 10)

In [3]:
arr_ravel = arr.ravel()

In [9]:
arr_ravel

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49])

In [7]:
arr[0,0] = 1000

In [8]:
arr

array([[1000,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49]])

In [5]:
arr_flatten = arr.flatten()

In [10]:
arr_flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

* pandas

In [11]:
import pandas as pd
pd.__version__

u'0.20.2'

In [12]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])
sample_df.head()

Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31

* slice
 - loc으로 slicing 할 경우, start, end 모두 포함

In [ ]:
sample_df.loc['MMM':'ACN']

In [13]:
#apple_df = pd.read_csv('apple.csv', header = None)
apple_df = pd.read_csv('apple.csv')
#print apple_df[:10]
apple_df.head()

Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442

In [14]:
# loc의 경우 start, end모두 포함
apple_df.loc[0:3]

Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412

In [15]:
apple_df.iloc[0:3]

Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085

* ix method deprecated
      - loc, iloc으로 대체하여 사용

In [ ]:
apple_df.ix[0:3]

* column selection
 - 정확한 컬럼의 이름으로 선택 가능

In [16]:
apple_df = pd.read_csv('apple.csv', header=None)
apple_df.head()

0       1       2       3       4         5
0       Date    Open    High     Low   Close    Volume
1  30-Sep-16  112.46  113.37  111.80  113.05  36379106
2  29-Sep-16  113.16  113.80  111.80  112.18  35886990
3  28-Sep-16  113.69  114.64  113.43  113.95  29641085
4  27-Sep-16  113.00  113.18  112.34  113.09  24607412

In [ ]:
apple_df[['Date', 'Close', 'Volume']].head()

In [ ]:
apple_df[[0, 1, 3]].head()

In [ ]:
apple_df = pd.read_csv('apple.csv')
apple_df.head()

In [ ]:
apple_df[['Date', 'Close', 'Volume']].head()

In [ ]:
apple_df[[0, 1, 3]].head()

* 데이터 중복 처리

In [18]:
copy = sample_df.copy()
df1 = copy.iloc[0:3].copy()
print df1

# append 함수 사용
copy = copy.append(df1)
print copy.tail()

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
ABBV                 AbbVie  Health Care   64.16        2.87
                       Name       Sector   Price  Book Value
Symbol                                                      
ZION          Zions Bancorp   Financials   24.74       33.23
ZTS                  Zoetis  Health Care   48.50        2.35
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
ABBV                 AbbVie  Health Care   64.16        2.87


In [19]:
copy.duplicated()

Symbol
MMM      False
ABT      False
ABBV     False
ACN      False
ATVI     False
AYI      False
ADBE     False
AAP      False
AES      False
AET      False
AMG      False
AFL      False
A        False
APD      False
AKAM     False
ALK      False
ALB      False
AA       False
ALXN     False
ALLE     False
AGN      False
ADS      False
LNT      False
ALL      False
GOOGL    False
GOOG     False
MO       False
AMZN     False
AEE      False
AAL      False
         ...  
WMT      False
WBA      False
WM       False
WAT      False
WFC      False
HCN      False
WDC      False
WU       False
WRK      False
WY       False
WHR      False
WFM      False
WMB      False
WLTW     False
WEC      False
WYN      False
WYNN     False
XEL      False
XRX      False
XLNX     False
XL       False
XYL      False
YHOO     False
YUM      False
ZBH      False
ZION     False
ZTS      False
MMM       True
ABT       True
ABBV      True
Length: 507, dtype: bool

In [ ]:
copy.drop_duplicates()